/**
 * Bundles the Vercel serverless function into a single self-contained CJS
 * file at api/[...all].js. Commit the output: Vercel deploys it as-is, so the
 * function has no external ESM dependency at runtime (genlayer-js is inlined),
 * avoiding ERR_REQUIRE_ESM on Vercel's function runtime.
 *
 * Usage: npm run build:api
 */
const { build } = require("esbuild");

build({
  entryPoints: ["server/src/vercel-entry.ts"],
  outfile: "api/[...all].js",
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  banner: {
    js: "/* Episteme Vercel function bundle - generated by npm run build:api */",
  },
}).catch(() => process.exit(1));
